using System;using System.IO;using Emberfall.Editor;using UnityEditor;using UnityEditor.Build;using UnityEditor.Build.Reporting;using UnityEngine;
namespace UnityEngine {
 public enum UIOrientation{AutoRotation} public enum FullScreenMode{FullScreenWindow}
 public static class Application{public static string dataPath;public static bool isBatchMode=true;}
 public static class Debug{public static void Log(string s){}}
}
namespace UnityEngine.Rendering{public enum GraphicsDeviceType{OpenGLES3}}
namespace UnityEditor.Build{public struct NamedBuildTarget{public static NamedBuildTarget Android=>new NamedBuildTarget();}public class BuildFailedException:Exception{public BuildFailedException(string s):base(s){}}}
namespace UnityEditor.Build.Reporting{public enum BuildResult{Succeeded,Failed}public class BuildSummary{public BuildResult result;}public class BuildReport{public BuildSummary summary=new BuildSummary();}}
namespace UnityEditor{
 [AttributeUsage(AttributeTargets.Method)]public class MenuItem:Attribute{public MenuItem(string s,bool b,int i){}}
 public enum ScriptingImplementation{Mono2x,IL2CPP}public enum ApiCompatibilityLevel{NET_Standard_2_0}public enum AndroidArchitecture{ARM64}public enum AndroidSdkVersions{AndroidApiLevelAuto=0,AndroidApiLevel26=26}public enum BuildTarget{StandaloneWindows64,Android}public enum BuildTargetGroup{Android}public enum BuildOptions{Development}
 public static class PlayerSettings{
  public static string Identifier;public static ScriptingImplementation Backend;public static ApiCompatibilityLevel Api;public static UIOrientation defaultInterfaceOrientation;public static bool allowedAutorotateToLandscapeLeft,allowedAutorotateToLandscapeRight,allowedAutorotateToPortrait=true,allowedAutorotateToPortraitUpsideDown=true,runInBackground=true,DefaultGraphics=true;public static FullScreenMode fullScreenMode;public static UnityEngine.Rendering.GraphicsDeviceType[] Graphics;
  public static void SetApplicationIdentifier(NamedBuildTarget t,string s){Identifier=s;}public static void SetScriptingBackend(NamedBuildTarget t,ScriptingImplementation s){Backend=s;}public static void SetApiCompatibilityLevel(NamedBuildTarget t,ApiCompatibilityLevel s){Api=s;}public static void SetUseDefaultGraphicsAPIs(BuildTarget t,bool b){DefaultGraphics=b;}public static void SetGraphicsAPIs(BuildTarget t,UnityEngine.Rendering.GraphicsDeviceType[] g){Graphics=g;}
  public static class Android{public static AndroidArchitecture targetArchitectures;public static AndroidSdkVersions minSdkVersion,targetSdkVersion;public static int bundleVersionCode;public static bool useCustomKeystore;}
 }
 public static class EditorUserBuildSettings{public static BuildTarget activeBuildTarget=BuildTarget.Android;public static bool buildAppBundle=true,exportAsGoogleAndroidProject=true;}
 public struct BuildPlayerOptions{public string[] scenes;public BuildTarget target;public BuildTargetGroup targetGroup;public string locationPathName;public BuildOptions options;}
 public static class BuildPipeline{public static bool Supported=true,Throw,Fail,Missing;public static int Calls;public static BuildPlayerOptions Last;public static bool IsBuildTargetSupported(BuildTargetGroup g,BuildTarget t)=>Supported;public static BuildReport BuildPlayer(BuildPlayerOptions p){Calls++;Last=p;if(EditorUserBuildSettings.buildAppBundle||EditorUserBuildSettings.exportAsGoogleAndroidProject)throw new Exception("wrong output mode");if(Throw)throw new InvalidOperationException("injected engine error");if(!Missing&&!Fail)File.WriteAllText(p.locationPathName,"managed test fixture, not an APK");return new BuildReport{summary=new BuildSummary{result=Fail?BuildResult.Failed:BuildResult.Succeeded}};}}
 public static class AssetDatabase{public static void SaveAssets(){}}public static class EditorUtility{public static void RevealInFinder(string s){}}
}
namespace Emberfall.Editor{public static class ProjectTools{public static int Calls;public static void EnsureSettings(){Calls++;}}public static class ProgressionValidation{public static void Validate(){}}}
public static class AndroidBuildBoundaryTests{
 static int checks;static void C(bool v,string s){checks++;if(!v)throw new Exception(s);}static void Reject(Action a,string s){try{a();throw new Exception("did not reject: "+s);}catch(BuildFailedException){checks++;}}
 public static void Run(string root){Directory.CreateDirectory(Path.Combine(root,"Assets/Scenes"));Application.dataPath=Path.Combine(root,"Assets");string scene=Path.Combine(root,AndroidBuild.ScenePath);File.WriteAllText(scene,"test-only scene boundary");string output=Path.Combine(root,"Builds/Android/Emberfall-Android.apk");
 AndroidBuild.Configure();C(PlayerSettings.Identifier=="com.h644782259.emberfall.android"&&PlayerSettings.Backend==ScriptingImplementation.IL2CPP&&PlayerSettings.Android.targetArchitectures==AndroidArchitecture.ARM64,"Android identity, backend and ABI configured");C((int)PlayerSettings.Android.minSdkVersion==26&&(int)PlayerSettings.Android.targetSdkVersion==0,"minimum SDK and installed target selected");C(!PlayerSettings.allowedAutorotateToPortrait&&!PlayerSettings.allowedAutorotateToPortraitUpsideDown&&PlayerSettings.allowedAutorotateToLandscapeLeft&&PlayerSettings.allowedAutorotateToLandscapeRight&&!PlayerSettings.runInBackground,"landscape and background policy");C(!PlayerSettings.DefaultGraphics&&PlayerSettings.Graphics.Length==1&&PlayerSettings.Graphics[0]==UnityEngine.Rendering.GraphicsDeviceType.OpenGLES3,"explicit graphics backend");
 BuildPipeline.Supported=false;Reject(AndroidBuild.BuildApk,"missing Android support");BuildPipeline.Supported=true;EditorUserBuildSettings.activeBuildTarget=BuildTarget.StandaloneWindows64;Reject(AndroidBuild.BuildApk,"wrong active target");EditorUserBuildSettings.activeBuildTarget=BuildTarget.Android;PlayerSettings.Android.useCustomKeystore=true;Reject(AndroidBuild.BuildApk,"custom signing is not this debug entry");PlayerSettings.Android.useCustomKeystore=false;File.Delete(scene);Reject(AndroidBuild.BuildApk,"incomplete project");File.WriteAllText(scene,"test-only scene boundary");C(BuildPipeline.Calls==0&&ProjectTools.Calls==0,"preflight failures never invoke configuration or a build");
 AndroidBuild.BuildApk();C(BuildPipeline.Last.target==BuildTarget.Android&&BuildPipeline.Last.options==BuildOptions.Development&&BuildPipeline.Last.scenes.Length==1&&BuildPipeline.Last.scenes[0]==AndroidBuild.ScenePath,"actual build request targets Android development Main scene");C(File.Exists(output)&&EditorUserBuildSettings.buildAppBundle&&EditorUserBuildSettings.exportAsGoogleAndroidProject,"successful boundary restores editor output switches");int calls=BuildPipeline.Calls;Reject(AndroidBuild.BuildApk,"existing output");C(BuildPipeline.Calls==calls&&File.ReadAllText(output)=="managed test fixture, not an APK","existing output untouched");File.Delete(output);
 BuildPipeline.Throw=true;try{AndroidBuild.BuildApk();throw new Exception("engine exception swallowed");}catch(InvalidOperationException){checks++;}BuildPipeline.Throw=false;C(EditorUserBuildSettings.buildAppBundle&&EditorUserBuildSettings.exportAsGoogleAndroidProject,"engine exception restores switches");BuildPipeline.Fail=true;Reject(AndroidBuild.BuildApk,"failed report");BuildPipeline.Fail=false;BuildPipeline.Missing=true;Reject(AndroidBuild.BuildApk,"successful report without output");C(EditorUserBuildSettings.buildAppBundle&&EditorUserBuildSettings.exportAsGoogleAndroidProject,"all terminal paths restore switches");Console.WriteLine("PASS "+checks+" actual Android build entry control-flow assertions; Unity/BuildPipeline API boundaries are managed shims, no APK built");
 }
}
